# Generated by Django 6.0.3 on 2026-04-05 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('fotos', models.JSONField(blank=True, help_text='URLs de fotos', null=True)),
            ],
            options={
                'db_table': 'estabelecimentos',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cargo', models.CharField(choices=[('ADMIN', 'Administrador'), ('FUNCIONARIO', 'Funcionário')], default='FUNCIONARIO', max_length=20)),
                ('is_vip', models.BooleanField(default=False)),
                ('atende_domicilio', models.BooleanField(default=False)),
                ('raio_km', models.IntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('estabelecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profissionais', to='core.estabelecimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profissional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profissionais',
            },
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='core.estabelecimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='core.profissional')),
            ],
            options={
                'db_table': 'convites',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('duracao_min', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.estabelecimento')),
            ],
            options={
                'db_table': 'servicos',
            },
        ),
        migrations.AddField(
            model_name='profissional',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='profissionais', to='core.servico'),
        ),
    ]
