# Generated by Django 6.0.3 on 2026-05-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
