# Generated by Django 6.0.3 on 2026-05-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profissional_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='foto_banner',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/banner/'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/perfil/'),
        ),
        migrations.AddField(
            model_name='servico',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos_proprios', to='core.profissional'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.estabelecimento'),
        ),
    ]
