# Generated by Django 6.0.3 on 2026-05-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cliente'),
        ('core', '0003_profissional_foto_banner_profissional_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='core.profissional'),
        ),
    ]
