# Generated by Django 6.0.3 on 2026-04-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
